// <auto-generated />
namespace PostRoom.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Addedapartmentnumber : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedapartmentnumber));
        
        string IMigrationMetadata.Id
        {
            get { return "201304200838181_Added apartment number"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
